# Model under development

# TODO 
- how to deal with missingness

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd

from src.data.download_DHS import load_DHS_data

In [19]:
df = load_DHS_data()
df.shape

(10834, 7)

In [20]:
df.head()

,CountryName,DHS_CountryCode,SurveyYear,SurveyId,Indicator,IndicatorId,Value
0,Afghanistan,AF,2015,AF2015DHS,General fertility rate,FE_FRTR_W_GFR,175.0
1,Albania,AL,2008,AL2008DHS,General fertility rate,FE_FRTR_W_GFR,46.0
2,Albania,AL,2017,AL2017DHS,General fertility rate,FE_FRTR_W_GFR,57.0
3,Armenia,AM,2000,AM2000DHS,General fertility rate,FE_FRTR_W_GFR,56.0
4,Armenia,AM,2005,AM2005DHS,General fertility rate,FE_FRTR_W_GFR,58.0

In [22]:
df_wide = df.pivot(index='SurveyId', columns='IndicatorId', values='Value')

In [23]:
df_wide.head()

IndicatorId,AH_HINS_W_NON,AH_TOBC_M_NON,AH_TOBC_W_NON,AN_ANEM_W_ANY,AN_ANEM_W_MOD,AN_ANEM_W_SEV,AN_NUTS_W_OWT,AN_NUTS_W_SHT,AN_NUTS_W_TH2,CH_ARIS_C_ARI,...,RH_ANCP_W_SKP,RH_ANCP_W_TOT,RH_DELA_C_TOT,RH_DELP_C_DHF,RH_PAHC_W_PR1,WE_DMKH_W_WIF,WS_SRCE_H_IMP,WS_SRCE_H_PIP,WS_TLET_H_NIM,WS_WTRT_H_APP
SurveyId,,,,,,,,,,,,,,,,,,,,,
AF2015DHS,100.0,51.8,94.0,NaN,NaN,NaN,NaN,NaN,NaN,12.6,...,58.6,100.0,100.0,48.1,88.5,4.8,65.3,2.3,66.3,6.0
AL2008DHS,78.5,57.5,95.8,19.0,2.6,0.1,39.3,0.7,0.5,5.4,...,97.3,100.0,100.0,96.7,73.4,19.0,94.5,52.1,5.7,7.3
AL2017DHS,62.2,64.4,NaN,22.7,3.0,0.4,45.2,0.8,1.0,2.4,...,88.4,100.0,100.0,98.6,37.1,14.5,83.3,48.8,3.0,4.8
AM2000DHS,NaN,32.6,NaN,12.4,2.0,0.3,41.5,1.1,0.6,11.4,...,92.4,100.0,100.0,91.3,86.8,33.8,94.8,62.8,100.0,NaN
AM2005DHS,NaN,39.3,98.2,24.6,3.3,0.5,42.4,0.9,1.3,8.0,...,93.0,100.0,100.0,96.4,81.6,33.3,97.2,75.0,6.9,NaN

In [28]:
df_wide.isna().mean().sort_values(ascending=False)

IndicatorId
CP_CLAB_C_CHL    0.964744
FG_PPCG_C_NUM    0.945513
HC_SMKH_H_DLY    0.810897
HA_HIVP_B_HIV    0.769231
AH_HINS_W_NON    0.762821
DV_EXPV_W_12M    0.724359
HC_WIXQ_P_GNI    0.721154
DV_EXSV_W_EVR    0.717949
AH_TOBC_M_NON    0.705128
AN_ANEM_W_ANY    0.653846
AN_ANEM_W_MOD    0.653846
AN_ANEM_W_SEV    0.653846
FE_AAFB_W_M2A    0.647436
WS_WTRT_H_APP    0.641026
CN_ANMC_C_SEV    0.576923
CN_ANMC_C_ANY    0.573718
CN_ANMC_C_MOD    0.573718
AH_TOBC_W_NON    0.570513
RH_PAHC_W_PR1    0.554487
MM_MMRO_W_GFR    0.548077
WE_DMKH_W_WIF    0.503205
ED_LITR_W_LIT    0.467949
MA_AAFM_W_M2A    0.461538
FP_NADU_W_NUM    0.403846
AN_NUTS_W_OWT    0.349359
AN_NUTS_W_SHT    0.349359
HC_CKFL_H_SLD    0.349359
AN_NUTS_W_TH2    0.346154
FP_KMTA_W_MOD    0.339744
CH_ARIS_C_ARI    0.330128
CH_SZWT_C_L25    0.320513
CN_BRFI_C_1HR    0.301282
ED_EDUC_W_MYR    0.298077
RH_DELP_C_DHF    0.282051
RH_ANCN_W_N4P    0.275641
CN_NUTS_C_WH3    0.262821
CN_NUTS_C_WH2    0.262821
CN_NUTS_C_WA2    0.262821
CN_NUTS_C_WHP    0.262821
CN_NUTS_C_WA3    0.262821
CN_NUTS_C_HA2    0.259615
CN_NUTS_C_HA3    0.259615
CH_DIAR_C_DIA    0.224359
CH_VAC1_C_NON    0.217949
CH_FEVR_C_FEV    0.217949
RH_DELA_C_TOT    0.205128
CN_BFDR_C_MNE    0.176282
CN_BFDR_C_MNA    0.169872
WS_SRCE_H_PIP    0.147436
RH_ANCP_W_SKP    0.137821
RH_ANCP_W_TOT    0.131410
HC_ELEC_H_ELC    0.121795
WS_TLET_H_NIM    0.108974
ED_EDUC_W_CPR    0.108974
HC_FLRM_H_NAT    0.105769
WS_SRCE_H_IMP    0.102564
CM_HRFB_C_A1S    0.099359
FE_FRTR_W_GFR    0.019231
dtype: float64